apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-color
          image: kodekloud/webapp-color:v1
          ports:
            - name: http
              containerPort: 8080
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
spec:
  rules:
    - host: webapp.localhost # adapt it accordingly your ingress endpoint domain
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: webapp
                port:
                  name: http
